spring:
  application:
    name: observability-lab

  threads:
    virtual:
      enabled: false

server:
  port: 8080

  tomcat:
    mbeanregistry:
      enabled: true

    accesslog:
      enabled: true
      pattern: '%t %a "%r" %s %D'

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threaddump,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 100ms,500ms,1s,3s,5s,10s
    tags:
      application: ${spring.application.name}
